server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    proxy_set_header Range $http_range;
    proxy_set_header If-Range $http_if_range;
    proxy_no_cache $http_range;

    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "public, no-cache, proxy-revalidate";
    }

    location ~* \.(?:js|css|woff2?|png|jpg|jpeg|gif|svg|ico|webp)$ {
        expires 1y;
        add_header Cache-Control "public, max-age=31536000, immutable";
        access_log off;
    }
}