name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
      - preview

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Install dependencies
        run: npm install

      - name: Create .env file for script
        run: |
          echo "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}" >> .env
          echo "CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}" >> .env
          echo "CLOUDINARY_CLOUD_NAME=${{ vars.CLOUDINARY_CLOUD_NAME }}" >> .env
          echo "CLOUDINARY_FOLDER_GALLERY=${{ vars.CLOUDINARY_FOLDER_GALLERY }}" >> .env
          echo "CLOUDINARY_FOLDER_MUSIC_TRACKS=${{ vars.CLOUDINARY_FOLDER_MUSIC_TRACKS }}" >> .env
          echo "CLOUDINARY_FOLDER_MUSIC_ARTWORKS=${{ vars.CLOUDINARY_FOLDER_MUSIC_ARTWORKS }}" >> .env

      - name: Build project
        run: npm run build

      - name: Deploy to Cloudflare Workers with Wrangler
        uses: cloudflare/wrangler-action@v3.14.1
        env:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=ragapuspa